const SET_LEVEL = "SET_LEVEL";
const SET_PLAYER = "SET_PLAYER";
const SET_DIFFICULTY = "SET_DIFFICULTY";
const COMPLETE_TUTORIAL = "COMPLETE_TUTORIAL";
const RESET_GAME = "RESET_GAME";
const NEXT_LEVEL = "NEXT_LEVEL";
const GET_TUTORIAL_STORAGE = "GET_TUTORIAL_STORAGE";
const END_OF_RUN = "END_OF_RUN";
const SET_COINS_THIS_RUN = "SET_COINS_THIS_RUN";
const OPEN_DAILY_MODAL = "OPEN_DAILY_MODAL";
const CLOSE_DAILY_MODAL = "CLOSE_DAILY_MODAL";
const SET_DAILY_TIMER = "SET_DAILY_TIMER";
const OPEN_DIFFICULTY_MODAL = "OPEN_DIFFICULTY_MODAL";
const CLOSE_DIFFICULTY_MODAL = "CLOSE_DIFFICULTY_MODAL";
const GET_DAILY_TIP = "GET_DAILY_TIP";

const UPDATE_FIELD = "UPDATE_FIELD";
const SET_TOTAL_BOMBS = "SET_TOTAL_BOMBS";
const SET_TOTAL_POINTS = "SET_TOTAL_POINTS";
const SET_MULTIPLIER = "SET_MULTIPLIER";
const SET_TOTAL_COINS = "SET_TOTAL_COINS";
const TILE_FLIPPED = "TILE_FLIPPED";
const BOMB_FLIPPED = "BOMB_FLIPPED";
const LEVEL_WON = "LEVEL_WON";
const INCREASE_COINS = "INCREASE_COINS";
const SET_OBTAINED_COINS = "SET_OBTAINED_COINS";
const DISABLE_TILES = "DISABLE_TILES";
const UNDISABLE_TILES = "UNDISABLE_TILES";
const BEGIN_SECOND_CHANCE = "BEGIN_SECOND_CHANCE";
const CANCEL_SECOND_CHANCE = "CANCEL_SECOND_CHANCE";
const TILE_RESET = "TILE_RESET";
const FLIP_TILE_BACK = "FLIP_TILE_BACK";
const REDUCE_SPECIAL_TICKET = "REDUCE_SPECIAL_TICKET";
const TIMER_FLIP = "TIMER_FLIP";
const TIMER_RESET = "TIMER_RESET";
const TIMER_RESET_CONFIRM = "TIMER_RESET_CONFIRM";
const LOAD_TIMER = "LOAD_TIMER";
const LOAD_TIMER_CONFIRM = "LOAD_TIMER_CONFIRM";

const PLAY_AS_GUEST = "PLAY_AS_GUEST";
const INCREASE_USER_COINS = "INCREASE_USER_COINS";
const INCREASE_SPECIAL_TICKETS = "INCREASE_SPECIAL_TICKETS";
const GET_USER_SESSION = "GET_USER_SESSION";
const GET_USER_COINS = "GET_USER_COINS";
const GET_SPECIAL_TICKETS = "GET_SPECIAL_COINS";
const LOGGED_IN = "LOGGED_IN";
const CLOSE_BONUS_MODAL = "CLOSE_BONUS_MODAL";
const GET_FIRST_TIME = "GET_FIRST_TIME";
const SET_USER_INFO = "SET_USER_INFO";
const BUY_MOUSE = "BUY_MOUSE";
const INCREASE_SPECIAL_TICKET = "INCREASE_SPECIAL_TICKET";
const ENABLE_TEMP_MOUSE = "ENABLE_TEMP_MOUSE";
const DISABLE_TEMP_MOUSE = "DISABLE_TEMP_MOUSE";

const TOGGLE_MEMO = "TOGGLE_MEMO";
const SET_FIELD = "SET_FIELD";
const SET_CURRENT_TILE = "SET_CURRENT_TILE";
const TOGGLE_VALUE = "TOGGLE_VALUE";

const LOAD_EASY_PERSONAL = "LOAD_EASY_PERSONAL";
const LOAD_NORMAL_PERSONAL = "LOAD_NORMAL_PERSONAL";
const LOAD_EXPERT_PERSONAL = "LOAD_EXPERT_PERSONAL";
const INCREASE_COMPLETE_EASY = "INCREASE_COMPLETE_EASY";
const INCREASE_COMPLETE_NORMAL = "INCREASE_COMPLETE_NORMAL";
const INCREASE_COMPLETE_EXPERT = "INCREASE_COMPLETE_EXPERT";
const INCREASE_INITIAL_EASY = "INCREASE_INITIAL_EASY";
const INCREASE_INITIAL_NORMAL = "INCREASE_INITIAL_NORMAL";
const INCREASE_INITIAL_EXPERT = "INCREASE_INITIAL_EXPERT";
const LOAD_EASY_GLOBAL = "LOAD_EASY_GLOBAL";
const LOAD_NORMAL_GLOBAL = "LOAD_NORMAL_GLOBAL";
const LOAD_EXPERT_GLOBAL = "LOAD_EXPERT_GLOBAL";

export {
  SET_LEVEL,
  SET_PLAYER,
  SET_DIFFICULTY,
  UPDATE_FIELD,
  SET_TOTAL_BOMBS,
  SET_TOTAL_POINTS,
  SET_MULTIPLIER,
  SET_TOTAL_COINS,
  TILE_FLIPPED,
  BOMB_FLIPPED,
  LEVEL_WON,
  PLAY_AS_GUEST,
  COMPLETE_TUTORIAL,
  RESET_GAME,
  NEXT_LEVEL,
  TOGGLE_MEMO,
  SET_FIELD,
  SET_CURRENT_TILE,
  TOGGLE_VALUE,
  INCREASE_COINS,
  SET_OBTAINED_COINS,
  INCREASE_USER_COINS,
  GET_USER_SESSION,
  GET_USER_COINS,
  GET_TUTORIAL_STORAGE,
  END_OF_RUN,
  DISABLE_TILES,
  SET_COINS_THIS_RUN,
  INCREASE_SPECIAL_TICKETS,
  GET_SPECIAL_TICKETS,
  BEGIN_SECOND_CHANCE,
  CANCEL_SECOND_CHANCE,
  TILE_RESET,
  REDUCE_SPECIAL_TICKET,
  UNDISABLE_TILES,
  OPEN_DAILY_MODAL,
  CLOSE_DAILY_MODAL,
  SET_DAILY_TIMER,
  OPEN_DIFFICULTY_MODAL,
  CLOSE_DIFFICULTY_MODAL,
  GET_DAILY_TIP,
  TIMER_FLIP,
  TIMER_RESET,
  TIMER_RESET_CONFIRM,
  LOAD_TIMER,
  LOAD_TIMER_CONFIRM,
  LOAD_EASY_PERSONAL,
  LOAD_NORMAL_PERSONAL,
  LOAD_EXPERT_PERSONAL,
  INCREASE_COMPLETE_EASY,
  INCREASE_COMPLETE_NORMAL,
  INCREASE_COMPLETE_EXPERT,
  INCREASE_INITIAL_EASY,
  INCREASE_INITIAL_NORMAL,
  INCREASE_INITIAL_EXPERT,
  LOGGED_IN,
  CLOSE_BONUS_MODAL,
  GET_FIRST_TIME,
  SET_USER_INFO,
  BUY_MOUSE,
  INCREASE_SPECIAL_TICKET,
  FLIP_TILE_BACK,
  LOAD_EASY_GLOBAL,
  LOAD_NORMAL_GLOBAL,
  LOAD_EXPERT_GLOBAL,
  ENABLE_TEMP_MOUSE,
  DISABLE_TEMP_MOUSE
};
